<h1>Bienvenue sur Airbnb</h1>
<ul>
    <li><a href="/users/add">Créer un compte</a></li>
    <li><a href="/users/login">Se connecter</a></li>
</ul>

<h2> Locations </h2>
<div class="card" style="width: 18rem;">
    <?php if (!empty($accommodations)) : ?>
        <ul>
            <?php foreach ($accommodations as $accommodation): ?>
                <li>
                    <ul>
                        <li>id : <?php echo $accommodation->getId() ?></li>
                        <li>adresse_id : <?php echo $accommodation->getAdresseId() ?></li>
                        <li>price : <?php echo $accommodation->getPrice() ?></li>
                        <li>id_type : <?php echo $accommodation->getIdType() ?></li>
                        <li>size : <?php echo $accommodation->getSize() ?></li>
                        <li>description : <?php echo $accommodation->getDescripton() ?></li>
                        <li>beds : <?php echo $accommodation->getBeds() ?></li>
                        <li>owner_id : <?php echo $accommodation->getOwnerId() ?></li>
                        <li>image : <?php echo $accommodation->getImage() ?> </li>
                    </ul>
                </li>
            <?php endforeach ?>
        </ul>
</div>
<?php else: ?>
    <div>Aucune location disponible</div>
<?php endif ?>