<h1>Bienvenue sur Airbnb</h1>
<?php
// On veux cacher le ul une fois connecté
if (isset($_SESSION['user'])) {
    $firstname = $_SESSION['user']->getFirstname();
} else {
    $firstname = ''; // Valeur par défaut si la clé n'est pas présente
}
if ($firstname == '') {
?>
    <ul>
        <li><a href="/users/add">Créer un compte</a></li>
        <li><a href="/users/login">Se connecter</a></li>
    </ul>
<?php
} else {
?>
    <ul>
        <!-- <li><a href="/profil">Mon profil</a></li> -->
        <li><a href="/users/listaccomodation/<?php echo $_SESSION['user']->getId() ?>">Voir mes annonces</a></li>
        <li><a href="/">Mes Réservations</a></li>
        <li><a href="/users/addaccommodation">Ajouter une location</a></li>
        <li><a href="/">Se déconnecter</a></li>
    </ul>
<?php
}
?>
<h2> Locations </h2>
<?php

?>
<p>Bonjour <?php echo htmlspecialchars($firstname); ?></p>
<div class="card" style="width: 18rem;">
    <?php
    if (!empty($accommodations)) : ?>
        <ul>
            <?php foreach ($accommodations as $accommodation): ?>
                <li>
                    <ul>
                        <li>id : <?php echo $accommodation->getId() ?></li>
                        <li>adresse_id : <?php echo $accommodation->getAdresseId() ?></li>
                        <li>price : <?php echo $accommodation->getPrice() ?></li>
                        <li>id_type : <?php echo $accommodation->getIdType() ?></li>
                        <li>size : <?php echo $accommodation->getSize() ?></li>
                        <li>description : <?php echo $accommodation->getDescription() ?></li>
                        <li>beds : <?php echo $accommodation->getBeds() ?></li>
                        <li>owner_id : <?php echo $accommodation->getOwnerId() ?></li>
                        <li>image : <?php echo $accommodation->getImage() ?> </li>
                        <li>
                            <?php if (isset($_SESSION['user'])): ?>
                                <a href="/users/create-rental" class="protected-link">Louer</a>
                            <?php else: ?>
                                <a href="/users/login" class="protected-link">Louer</a>
                            <?php endif; ?>
                        </li>
                    </ul>
                </li>
            <?php endforeach ?>
        </ul>
</div>
<?php else: ?>
    <div>Aucune location disponible</div>
<?php endif ?>