<!DOCTYPE html>
<html lang="fr">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title><?php echo $title ?></title>
</head>

<body>
    <!-- <div class="navbar">
        <nav>
            <ul>
                <li><a href="/">Accueil</a></li>
                <ul>Profils
                    <li><a href="/profil">Mon profil</a></li>
                    <li><a href="/">Se déconnecter</a></li>
                    <li><a href="/profil">Mes locations</a></li>
                    <li><a href="/biens">Mes biens</a></li>
                </ul>
                <li><a href="/users/add">Connexion</a></li>
            </ul>
        </nav>
    </div> -->