<?php
if (isset($_GET['accommodation_id'])) {
    $accommodation_id = $_GET['accommodation_id'];
} else {
    // Handle the case where the accommodation_id is not set
    $accommodation_id = '';
}
?>
<script>
    document.getElementById('accommodation_id').value = "<?php echo $accommodation_id; ?>";
</script>

<div>
    <ul>
        <li><a href="/">🔙 Retour</a></li>
    </ul>
</div>
<h1>Ajouter une location</h1>
<form action="/users/submit-rental" method="post">
    <h2>Formulaire de location</h2>

    <div>
        <label for="user_id">ID de l'utilisateur :</label>
        <input type="number" id="user_id" name="user_id" required>
    </div>

    <input type="hidden" id="accommodation_id" name="accommodation_id" value="">

    <div>
        <label for="date_start">Date de début :</label>
        <input type="datetime-local" id="date_start" name="date_start" required>
    </div>

    <div>
        <label for="date_end">Date de fin :</label>
        <input type="datetime-local" id="date_end" name="date_end" required>
    </div>

    <button type="submit">Soumettre la location</button>
</form>