<h1>Ajouter une location</h1>
<form action="" method="post" novalidate>
    <div>
        <label for="input-country">Pays :</label>
        <input type="text" name="country" id="input-country">
    </div>
    <div>
        <label for="input-city">Ville :</label>
        <input type="text" name="city" id="input-city">
    </div>
    <div>
        <label for="input-adress">Adresse postale :</label>
        <input type="number" name="adress" id="input-adress">
    </div>
    <div>
        <label for="input-postal_code">Code postal :</label>
        <input type="number" name="postal_code" id="input-postal_code">
    </div>
    <div>
        <label for="input-price">Prix :</label>
        <input type="number" name="price" id="input-price">
    </div>
    <div>
        <label for="input-id_type">Type de bien :</label>
        <input type="texte" name="id_type" id="input-id_type">
    </div>
    <div>
        <label for="input-size">Taille :</label>
        <input type="number" name="size" id="input-size">
    </div>
    <div>
        <label for="input-description">Description :</label>
        <input type="text" name="description" id="input-description">
    </div>
    <div>
        <label for="input-beds">Couchages :</label>
        <input type="number" name="beds" id="input-beds">
    </div>
    <div>
        <label for="input-owner_id">Propriétaire :</label>
        <input type="Text" name="owner_id" id="input-owner_id">
    </div>
    <label for="input-image">Image :</label>
    <input type="image" name="image" id="input-image">
    <div>
        <input type="submit" value="Ajouter">
    </div>

</form>