<div>
    <ul>
        <li><a href="/">🔙 Retour</a></li>
        <li><a href="/users/login">Se connecter</a></li>
    </ul>
</div>
<h1>Créer mon compte</h1>
<form action="/users" method="post" novalidate>
    <div>
        <label for="input-email">Email :</label>
        <input type="email" name="email" id="input-email">
    </div>
    <div>
        <label for="input-password">Mot de passe :</label>
        <input type="password" name="password" id="input-password">
    </div>
    <div>
        <label for="input-firstname">Prénom :</label>
        <input type="text" name="firstname" id="input-firstname">
    </div>
    <div>
        <label for="input-lastname">Nom :</label>
        <input type="text" name="lastname" id="input-lastname">
    </div>
    <div>
        <label for="input-phone_number">Téléphone :</label>
        <input type="tel" name="phone_number" id="input-phone_number">
    </div>
    <div>
        <label for="input-role">Role :</label>
        <input type="radio" name="role" id="input-role" value="0">Locataire
        <input type="radio" name="role" id="input-role" value="1">Loueur
    </div>
    <div>
        <input type="submit" value="Ajouter">
    </div>

</form>