<h1>Ajouter une location</h1>
<form action="/users/addaccommodation" method="post" novalidate>
    <input type="hidden" name="owner_id" value="<?php echo $_SESSION["id"] ?>">
    <div>
        <label for="input-country">Pays :</label>
        <input type="text" name="country" id="input-country">
    </div>
    <div>
        <label for="input-city">Ville :</label>
        <input type="text" name="city" id="input-city">
    </div>
    <div>
        <label for="input-adress">Adresse postale :</label>
        <input type="text" name="adress" id="input-adress">
    </div>
    <div>
        <label for="input-postal_code">Code postal :</label>
        <input type="number" name="postal_code" id="input-postal_code">
    </div>
    <div>
        <label for="input-price">Prix :</label>
        <input type="number" name="price" id="input-price">
    </div>
    <!-- Insérer une liste déroulante pour sélectionner 1 seule choix récupéré depuis la table "accommodations_types" -->
    <div>
        <label for="select-id_type">Type de bien :</label>
        <select name="id_type" id="select-id_type">
            <option value="">Choisissez...</option>
            <!-- Insertion des éléments des équipements -->
            <?php foreach ($types_accommodations  as $type) : ?>
                <option value="<?= $type->getId() ?>"><?= $type->getTypeAccommodation() ?></option>
            <?php endforeach; ?>
        </select>
    </div>
    <div>
        <label for="input-size">Taille :</label>
        <input type="number" name="size" id="input-size">
    </div>
    <div>
        <label for="input-description">Description :</label>
        <input type="text" name="description" id="input-description">
    </div>
    <div>
        <label for="input-beds">Couchages :</label>
        <input type="number" name="beds" id="input-beds">
    </div>
    <label for="input-image">Image :</label>
    <input type="file" name="image" id="input-image">
    <div>
        <input type="submit" value="Ajouter">
    </div>

</form>