<div>
    <button><a href="/">🏠 Retour</a></button>
</div>

<form action="/users/create-rental/<?php echo $accommodation->getId(); ?>" method="post" novalidate>
    <h2>Formulaire de location</h2>

    <div>
        <input type="hidden" id="user_id" name="user_id" value="<?php echo $_SESSION['user']->getId(); ?>">
    </div>

    <!-- Récupérer l'id de l'accommodation à louer il est deja présent dans l'url -->
    <div>
        <input type="hidden" id="accommodation_id" name="accommodation_id" value="<?php echo $accommodation->getId(); ?>">
    </div>


    <div>
        <label for="date_start">Date de début :</label>
        <input type="datetime-local" id="date_start" name="date_start" required>
    </div>

    <div>
        <label for="date_end">Date de fin :</label>
        <input type="datetime-local" id="date_end" name="date_end" required>
    </div>

    <button type="submit">Soumettre la location</button>
</form>