<div>
    <button><a href="/">🏠 Retour</a></button>
</div>

<h1>Mes annonces</h1>

<div>
    <button><a href="/users/addaccommodation">Ajouter une location</a></button>
</div>

<?php
if (!empty($accommodations)): ?>
    <ul>
        <?php foreach ($accommodations as $accommodation): ?>
            <li>
                <ul>
                    <li>country : <?php echo $accommodation->getAdress()->getCity() ?></li>
                    <li>city : <?php echo $accommodation->getAdress()->getCountry() ?></li>
                    <li>price : <?php echo $accommodation->getPrice() ?></li>
                    <li>size : <?php echo $accommodation->getSize() ?></li>
                    <li>description : <?php echo $accommodation->getDescription() ?></li>
                    <li>beds : <?php echo $accommodation->getBeds() ?></li>
                    <li>image : <?php echo $accommodation->getImage() ?> </li>
                    <li><a href="/users/create-rental">Louer</a></li>
                </ul>
            </li>
        <?php endforeach ?>
    </ul>
<?php else: ?>
    <div>Vous avez aucune annonce définie.</div>
<?php endif ?>