<nav>
    <div>
        <button><a href="/">🏠 Retour</a></button>
    </div>
</nav>
<h1>Mes locations</h1>

<?php
if (!empty($rentals)): ?>
    <div class="accommodations-list">
        <?php foreach ($rentals as $rental): ?>
            <div class="accommodation-item3">
                <ul>
                    <li>Date de début : <?php echo $rental->getDateStart()->format('Y-m-d H:i:s'); ?></li>
                    <li>Date de fin : <?php echo $rental->getDateEnd()->format('Y-m-d H:i:s'); ?></li>
                </ul>
            </div>
        <?php endforeach ?>
    </div>
<?php else: ?>
    <div>Vous n'avez aucune réservation.</div>
<?php endif ?>