<nav>
    <div>
        <button><a href="/">🏠 Retour</a></button>
    </div>
</nav>

<h1>Mes annonces</h1>

<div>
    <button><a href="/users/addaccommodation">Ajouter une location</a></button>
</div>

<?php
if (!empty($accommodations)): ?>
    <div class="accommodations-list">
        <?php foreach ($accommodations as $accommodation): ?>
            <div class="accommodation-item2">
                <ul>
                    <li>Pays : <?php echo $accommodation->getAdress()->getCity() ?></li>
                    <li>Ville : <?php echo $accommodation->getAdress()->getCountry() ?></li>
                    <li>Prix : <?php echo $accommodation->getPrice() ?></li>
                    <li>Taille : <?php echo $accommodation->getSize() ?></li>
                    <li>Description : <?php echo $accommodation->getDescription() ?></li>
                    <li>Couchages : <?php echo $accommodation->getBeds() ?></li>
                    <li>image : <?php echo $accommodation->getImage() ?> </li>
                </ul>
            </div>
        <?php endforeach ?>
    </div>
<?php else: ?>
    <div>Vous avez aucune annonce définie.</div>
<?php endif ?>