<nav>
    <div>
        <button><a href="/">🏠 Retour</a></button>
    </div>
    <div>
        <button><a href="/users/add">S'inscrire</a></button>
    </div>
</nav>

<h1>Connexion</h1>

<form action="/users/login" method="post" novalidate>
    <div>
        <label for="input-email">Email :</label>
        <input type="email" name="email" id="input-email">
    </div>
    <div>
        <label for="input-password">Mot de passe :</label>
        <input type="password" name="password" id="input-password">
    </div>
    <div>
        <input type="submit" value="Connexion">
    </div>
</form>